name: ObjectDetectionRL
channels:
  - anaconda
  - conda-forge
  # - nvidia # TODO undo for computers with GPU
  - pytorch
dependencies:
  # - nvidia::cudatoolkit=11.1 # TODO undo for computers with GPU
  - pytorch::pytorch
  - matplotlib
  - torchvision
  - numpy
  - pip
  - pip:
    - opencv-python