name: ObjectDetectionRL
channels:
  - anaconda
  - conda-forge
  - nvidia
  - pytorch
dependencies:
  - nvidia::cudatoolkit=11.1
  - pytorch::pytorch
  - matplotlib
  - torchvision
  - numpy
  - pip
  - pip:
    - opencv-python